name: Process crawler

on:
  workflow_dispatch:

jobs:
  build:
    name: Process crawler
    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.9'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pandas==1.2.0 numpy==1.19.5 BeautifulSoup4==4.9.3 requests==2.28.1 urllib3==1.26.12 typer==0.6.1 python-decouple==3.6 pytest==7.1.3
        pip install get-chrome-driver --upgrade
        pip install -r requirements.txt
    - name: Build data
      run: |
        python3 crawler.py
    - name: Commit files
      run: |
        git config --local user.email "ube@coder.okinawa.jp"
        git config --local user.name "Tomoyuki UBE"
        git add data
        git diff-index --quiet HEAD || git commit -m "[BOT] crawler"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}
